# Generated by Django 4.1.5 on 2023-05-04 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_adminpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='admin_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.adminpost'),
        ),
    ]
