# Generated by Django 4.1.5 on 2023-01-21 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_case_status_case_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='action',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
