# Generated by Django 4.1.5 on 2023-05-04 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_admin_post'),
        ('main', '0002_alter_case_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='admin_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.adminpost'),
        ),
    ]
