# Generated by Django 4.1.5 on 2023-01-21 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_case_action_case_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
