# Generated by Django 4.1.5 on 2023-01-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_case_media_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
